version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "4000:4000"
  svelte:
    build:
      dockerfile: Dockerfile
      context: ./svelte
    ports:
      - "5000:5000"
