version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "4000:4000"
  client:
    build:
      dockerfile: Dockerfile
      context: ./gogo
    ports:
      - "3000:3000"
