version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "4000:4000"
  svelte:
    build:
      dockerfile: Dockerfile
      context: ./gogo
    ports:
      - "3000:3000"
